### ISSUE TITLE
Bug with new proofing system

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#165]
Good morning! I tested out the new proofing/editing system with one of our developers yesterday and she sent me some pages to approve and make live. After I made the pages live, the left side navigation was all screwed up and is listing pages that aren't supposed to be there and took out pages that need to be there. I logged in and tried to manually update the menu back to what it should be but it didn't do anything. If we could get this looked at sooner rather than later I would appreciate it!!

http://www.jccmi.edu/library/

Here is what the side menu should be:
![1](https://cloud.githubusercontent.com/assets/15264315/18784808/875085f4-8162-11e6-8d10-e899ae1516ed.png)

And here is what is appearing:
![2](https://cloud.githubusercontent.com/assets/15264315/18784812/8f3bc1fc-8162-11e6-9ec6-f53ccb236b2a.png)

I'm assuming it has something to new with the new editorial process? The library was the only section I approved pages on.

Thanks for your help with this!

**Comment by d4mation** [comment]
I've been trying to figure this out and I think I may have come across it just now.

Reading that last bit in the Issue you mentioned that the Library was "the only section you approved pages on", but on Live the Library isn't designated as a Section.

![image](https://cloud.githubusercontent.com/assets/7770631/18791872/60d2d2c2-8182-11e6-9a6c-ed5f77de8638.png)

When I clicked that Checkbox and set the Menu to "Library" it seemed to fix the Issue with the Menu on that page.

Could you confirm for that for me? I'm wondering if this is the problem and that somehow things got changed when we pushed those updates yesterday.

**Comment by d4mation** [comment]
I didn't save my changes, so you would need to check that box again if this is indeed the cause of the problem.

**Comment by banksashleym** [comment]
Ahh, yes that is exactly it, I am having to reselect that a page is a part of a site section when a user sends me changes.

**Comment by banksashleym** [comment]
This only happens when a user makes a change to the site section page, however, and not any of the child pages within that section. 

I switched to one of our developer site section accounts and made a change to a "site section" page and that did affect the menu. But when I made a change to one of the child pages within that section it did not have an effect on the menu and is working how it should be. However, when I went back into her account and clicked on "submit for review" a screen comes up and says "this site section does not belong to you." I went back under my admin account and checked her profile and she still does have access to her site section?

**Comment by d4mation** [comment]
Which User Accounts were you testing with and with which Pages? 

I want to be able to recreate this exactly within my local copy of the site so I can pin this bug down.

**Comment by banksashleym** [comment]
Sure! I switched to Karen Marler's account, she has access to the Academic Deans site section. I made a change on the main [academic deans page](https://www.jccmi.edu/academic-deans/), which is indicated as being a site section. I received the email notification and then clicked on the link in the email, accepted the changes (without clicking on the site section checkbox) and viewed the page on the live site and the menu was different. I then logged back into my account and made the academic deans page back into a site section. From there I switched back to Karen and made a change to the  [Adjunct Resources page](https://www.jccmi.edu/academic-deans/adjunct-resources/) (a child page of the academic deans page). When I clicked on "submit for review" got a screen that said "this site section doesn't belong to you" but I still did receive an email notification with the change and I was still able to accept changes and they showed up correctly on the live side without changing the menu.

**Comment by d4mation** [comment]
I ended up having to make a fresh copy of the Live site locally in order to reproduce this, but now I can see the problem and it is what I expected given the reproduction steps you typed out (Seriously, thanks for those!)

Basically when someone makes changes and requests approval, they are sending a new copy of that Post/Page to be reviewed. This copy does not have that Section Checkbox checked because it isn't there for them. That means when you go to review the changes, the Checkbox is no longer checked and it will then be overwritten to be unchecked when it is approved.

I'm going to have to find a way to make the Section Settings not be altered whenever changes by a Site Section Manager are made.

**Comment by banksashleym** [comment]
Oh wow, that sounds confusing! Good deal, don't feel like you have to get this figured out today. Now that we know what's going on I will make sure that if I am approving a site section page I will just have to re-establish it as a site section and add in the menu :) Thanks so much for all of your help!

**Comment by d4mation** [comment]
I am pretty sure I've come up with a fix for this! I've tested it a fair amount myself Locally, but I just created a branch for the JC User Roles plugin called `jc-theme-2015/issue/165/preserve-section-meta`.

If you could give that a whirl on Staging to ensure everything is in working order when you get the chance, I'll get this merged over to Live!

**Comment by banksashleym** [comment]
Thanks! I switched to user FieroJennifeR, she is a site section manager for the library and testing lab. However, when i go to her pages it is pulling all pages, and not just library and testing lab pages?

**Comment by d4mation** [comment]
That's very odd. I just switched to the same User within my Local copy of the site and I was only able to see the Library and Testing Lab pages. I'll investigate this more.

**Comment by d4mation** [comment]
I have just pushed a fix for this to the `jc-theme-2015/issue/165/preserve-section-meta` branch of JC User Roles. 

I implemented a check so that if User Role was undefined (Which it strangely was on Staging, but not in my Local Copy of the site), it will force a re-check to ensure the User isn't actually a Site Section Manager.

Now it should only show the 14 Pages (Within the two Page Sections assigned) for the User `FieroJennifeR` 👍

**Comment by banksashleym** [comment]
This is working great, thanks so much!!

**Comment by d4mation** [comment]
No problem! Changes are Live!

**Comment by banksashleym** [comment]
Hello! I just got a call and it seems that some users are still experiencing the "this site section does not belong to you" screen when they submit a page for review? I went through all of the users and tested them out, and most are working great with the exception of DunbarJoyceD, GrajekBrandyJ, MontgomTobyL, PonagaiJonathaD,

**Comment by d4mation** [comment]
Is this on the Staging that you tried this on? 

- I found a `TestUser` on Staging and assigned it to `Academic Deans`.
- I then switched to that User, made an Edit to the `Academic Deans` page.
- Submitted it for review.
- Switched back to my User account
- Approved the changes
- Switched back to `TestUser` and I could still edit the `Academic Deans` page.

**Comment by banksashleym** [comment]
Hi Eric, no this was on the live site that I was testing on. Thanks!

**Comment by d4mation** [comment]
I just followed the same steps I outlined above on Live with the same results. I don't seem to be getting the `this site section does not belong to you` error.

Can you give me some detailed reproduction steps? I must be missing something here. From what I can tell I've done the same thing that you outlined above (Since you got the error before switching their Site Section to another one).

**Comment by banksashleym** [comment]
Well that's weird, now it's not doing it with the TestUser account now. I just switched over to DunbarJoyceD account and ThirolfKathrynQ account and those two are still seeing the "this site section does not belong to you" error.

**Comment by d4mation** [comment]
I just managed to reproduce this.

The problem before was that I was editing the main Site Section Page. In this case it is triggering only on Pages _within_ the Site Section.

I'll look into this more.

**Comment by d4mation** [comment]
I just uploaded a possible fix to the Live Server. Could you check on that for me when you get the chance? It seems to solve the problem in my Local Environment.

**Comment by banksashleym** [comment]
Absolutely, this seems to be working great! I checked the two users I know that were having issues. Thank you!!
